using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyCompany("Corvalius")]
[assembly: AssemblyCopyright("Copyright © Corvalius - 2013")]
[assembly: NeutralResourcesLanguage("en")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:

// This is autogenerated using a powershell script. //
[assembly: AssemblyVersion("2.1.181")]
[assembly: AssemblyFileVersion("2.1.181")]
